/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as environmentRouteRouteImport } from './routes/(environment)/route'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as environmentornamentRouteRouteImport } from './routes/(environment)/(ornament)/route'
import { Route as environmentappsRouteRouteImport } from './routes/(environment)/(apps)/route'
import { Route as environmentornamentIndexRouteImport } from './routes/(environment)/(ornament)/index'
import { Route as environmentornamentPeopleRouteImport } from './routes/(environment)/(ornament)/people'
import { Route as environmentornamentEnvironmentsRouteImport } from './routes/(environment)/(ornament)/environments'
import { Route as environmentappsSettingsRouteRouteImport } from './routes/(environment)/(apps)/settings/route'
import { Route as environmentappsAppStoreRouteRouteImport } from './routes/(environment)/(apps)/app-store/route'
import { Route as environmentappsSettingsIndexRouteImport } from './routes/(environment)/(apps)/settings/index'
import { Route as environmentappsAppStoreIndexRouteImport } from './routes/(environment)/(apps)/app-store/index'
import { Route as environmentappsSettingsPeopleRouteImport } from './routes/(environment)/(apps)/settings/people'
import { Route as environmentappsSettingsEnvironmentsRouteImport } from './routes/(environment)/(apps)/settings/environments'
import { Route as environmentappsSettingsAppsRouteImport } from './routes/(environment)/(apps)/settings/apps'
import { Route as environmentappsSettingsAppearanceRouteImport } from './routes/(environment)/(apps)/settings/appearance'
import { Route as environmentappsSettingsAccessibilityRouteImport } from './routes/(environment)/(apps)/settings/accessibility'
import { Route as environmentappsAppStoreSearchRouteImport } from './routes/(environment)/(apps)/app-store/search'
import { Route as environmentappsAppStoreArcadeRouteImport } from './routes/(environment)/(apps)/app-store/arcade'
import { Route as environmentappsSettingsGeneralIndexRouteImport } from './routes/(environment)/(apps)/settings/general.index'
import { Route as environmentappsSettingsGeneralAboutRouteImport } from './routes/(environment)/(apps)/settings/general.about'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const environmentRouteRoute = environmentRouteRouteImport.update({
  id: '/(environment)',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const environmentornamentRouteRoute =
  environmentornamentRouteRouteImport.update({
    id: '/(ornament)',
    getParentRoute: () => environmentRouteRoute,
  } as any)
const environmentappsRouteRoute = environmentappsRouteRouteImport.update({
  id: '/(apps)',
  getParentRoute: () => environmentRouteRoute,
} as any)
const environmentornamentIndexRoute =
  environmentornamentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => environmentornamentRouteRoute,
  } as any)
const environmentornamentPeopleRoute =
  environmentornamentPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => environmentornamentRouteRoute,
  } as any)
const environmentornamentEnvironmentsRoute =
  environmentornamentEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => environmentornamentRouteRoute,
  } as any)
const environmentappsSettingsRouteRoute =
  environmentappsSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => environmentappsRouteRoute,
  } as any)
const environmentappsAppStoreRouteRoute =
  environmentappsAppStoreRouteRouteImport.update({
    id: '/app-store',
    path: '/app-store',
    getParentRoute: () => environmentappsRouteRoute,
  } as any)
const environmentappsSettingsIndexRoute =
  environmentappsSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsAppStoreIndexRoute =
  environmentappsAppStoreIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => environmentappsAppStoreRouteRoute,
  } as any)
const environmentappsSettingsPeopleRoute =
  environmentappsSettingsPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsSettingsEnvironmentsRoute =
  environmentappsSettingsEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsSettingsAppsRoute =
  environmentappsSettingsAppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsSettingsAppearanceRoute =
  environmentappsSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsSettingsAccessibilityRoute =
  environmentappsSettingsAccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsAppStoreSearchRoute =
  environmentappsAppStoreSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => environmentappsAppStoreRouteRoute,
  } as any)
const environmentappsAppStoreArcadeRoute =
  environmentappsAppStoreArcadeRouteImport.update({
    id: '/arcade',
    path: '/arcade',
    getParentRoute: () => environmentappsAppStoreRouteRoute,
  } as any)
const environmentappsSettingsGeneralIndexRoute =
  environmentappsSettingsGeneralIndexRouteImport.update({
    id: '/general/',
    path: '/general/',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsSettingsGeneralAboutRoute =
  environmentappsSettingsGeneralAboutRouteImport.update({
    id: '/general/about',
    path: '/general/about',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/app-store': typeof environmentappsAppStoreRouteRouteWithChildren
  '/settings': typeof environmentappsSettingsRouteRouteWithChildren
  '/environments': typeof environmentornamentEnvironmentsRoute
  '/people': typeof environmentornamentPeopleRoute
  '/': typeof environmentornamentIndexRoute
  '/app-store/arcade': typeof environmentappsAppStoreArcadeRoute
  '/app-store/search': typeof environmentappsAppStoreSearchRoute
  '/settings/accessibility': typeof environmentappsSettingsAccessibilityRoute
  '/settings/appearance': typeof environmentappsSettingsAppearanceRoute
  '/settings/apps': typeof environmentappsSettingsAppsRoute
  '/settings/environments': typeof environmentappsSettingsEnvironmentsRoute
  '/settings/people': typeof environmentappsSettingsPeopleRoute
  '/app-store/': typeof environmentappsAppStoreIndexRoute
  '/settings/': typeof environmentappsSettingsIndexRoute
  '/settings/general/about': typeof environmentappsSettingsGeneralAboutRoute
  '/settings/general/': typeof environmentappsSettingsGeneralIndexRoute
}
export interface FileRoutesByTo {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/environments': typeof environmentornamentEnvironmentsRoute
  '/people': typeof environmentornamentPeopleRoute
  '/': typeof environmentornamentIndexRoute
  '/app-store/arcade': typeof environmentappsAppStoreArcadeRoute
  '/app-store/search': typeof environmentappsAppStoreSearchRoute
  '/settings/accessibility': typeof environmentappsSettingsAccessibilityRoute
  '/settings/appearance': typeof environmentappsSettingsAppearanceRoute
  '/settings/apps': typeof environmentappsSettingsAppsRoute
  '/settings/environments': typeof environmentappsSettingsEnvironmentsRoute
  '/settings/people': typeof environmentappsSettingsPeopleRoute
  '/app-store': typeof environmentappsAppStoreIndexRoute
  '/settings': typeof environmentappsSettingsIndexRoute
  '/settings/general/about': typeof environmentappsSettingsGeneralAboutRoute
  '/settings/general': typeof environmentappsSettingsGeneralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(environment)': typeof environmentRouteRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/(environment)/(apps)': typeof environmentappsRouteRouteWithChildren
  '/(environment)/(ornament)': typeof environmentornamentRouteRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/(environment)/(apps)/app-store': typeof environmentappsAppStoreRouteRouteWithChildren
  '/(environment)/(apps)/settings': typeof environmentappsSettingsRouteRouteWithChildren
  '/(environment)/(ornament)/environments': typeof environmentornamentEnvironmentsRoute
  '/(environment)/(ornament)/people': typeof environmentornamentPeopleRoute
  '/(environment)/(ornament)/': typeof environmentornamentIndexRoute
  '/(environment)/(apps)/app-store/arcade': typeof environmentappsAppStoreArcadeRoute
  '/(environment)/(apps)/app-store/search': typeof environmentappsAppStoreSearchRoute
  '/(environment)/(apps)/settings/accessibility': typeof environmentappsSettingsAccessibilityRoute
  '/(environment)/(apps)/settings/appearance': typeof environmentappsSettingsAppearanceRoute
  '/(environment)/(apps)/settings/apps': typeof environmentappsSettingsAppsRoute
  '/(environment)/(apps)/settings/environments': typeof environmentappsSettingsEnvironmentsRoute
  '/(environment)/(apps)/settings/people': typeof environmentappsSettingsPeopleRoute
  '/(environment)/(apps)/app-store/': typeof environmentappsAppStoreIndexRoute
  '/(environment)/(apps)/settings/': typeof environmentappsSettingsIndexRoute
  '/(environment)/(apps)/settings/general/about': typeof environmentappsSettingsGeneralAboutRoute
  '/(environment)/(apps)/settings/general/': typeof environmentappsSettingsGeneralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/app-store'
    | '/settings'
    | '/environments'
    | '/people'
    | '/'
    | '/app-store/arcade'
    | '/app-store/search'
    | '/settings/accessibility'
    | '/settings/appearance'
    | '/settings/apps'
    | '/settings/environments'
    | '/settings/people'
    | '/app-store/'
    | '/settings/'
    | '/settings/general/about'
    | '/settings/general/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/environments'
    | '/people'
    | '/'
    | '/app-store/arcade'
    | '/app-store/search'
    | '/settings/accessibility'
    | '/settings/appearance'
    | '/settings/apps'
    | '/settings/environments'
    | '/settings/people'
    | '/app-store'
    | '/settings'
    | '/settings/general/about'
    | '/settings/general'
  id:
    | '__root__'
    | '/(environment)'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/(environment)/(apps)'
    | '/(environment)/(ornament)'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/(environment)/(apps)/app-store'
    | '/(environment)/(apps)/settings'
    | '/(environment)/(ornament)/environments'
    | '/(environment)/(ornament)/people'
    | '/(environment)/(ornament)/'
    | '/(environment)/(apps)/app-store/arcade'
    | '/(environment)/(apps)/app-store/search'
    | '/(environment)/(apps)/settings/accessibility'
    | '/(environment)/(apps)/settings/appearance'
    | '/(environment)/(apps)/settings/apps'
    | '/(environment)/(apps)/settings/environments'
    | '/(environment)/(apps)/settings/people'
    | '/(environment)/(apps)/app-store/'
    | '/(environment)/(apps)/settings/'
    | '/(environment)/(apps)/settings/general/about'
    | '/(environment)/(apps)/settings/general/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  environmentRouteRoute: typeof environmentRouteRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(environment)': {
      id: '/(environment)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof environmentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(environment)/(ornament)': {
      id: '/(environment)/(ornament)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof environmentornamentRouteRouteImport
      parentRoute: typeof environmentRouteRoute
    }
    '/(environment)/(apps)': {
      id: '/(environment)/(apps)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof environmentappsRouteRouteImport
      parentRoute: typeof environmentRouteRoute
    }
    '/(environment)/(ornament)/': {
      id: '/(environment)/(ornament)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof environmentornamentIndexRouteImport
      parentRoute: typeof environmentornamentRouteRoute
    }
    '/(environment)/(ornament)/people': {
      id: '/(environment)/(ornament)/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof environmentornamentPeopleRouteImport
      parentRoute: typeof environmentornamentRouteRoute
    }
    '/(environment)/(ornament)/environments': {
      id: '/(environment)/(ornament)/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof environmentornamentEnvironmentsRouteImport
      parentRoute: typeof environmentornamentRouteRoute
    }
    '/(environment)/(apps)/settings': {
      id: '/(environment)/(apps)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof environmentappsSettingsRouteRouteImport
      parentRoute: typeof environmentappsRouteRoute
    }
    '/(environment)/(apps)/app-store': {
      id: '/(environment)/(apps)/app-store'
      path: '/app-store'
      fullPath: '/app-store'
      preLoaderRoute: typeof environmentappsAppStoreRouteRouteImport
      parentRoute: typeof environmentappsRouteRoute
    }
    '/(environment)/(apps)/settings/': {
      id: '/(environment)/(apps)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof environmentappsSettingsIndexRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/app-store/': {
      id: '/(environment)/(apps)/app-store/'
      path: '/'
      fullPath: '/app-store/'
      preLoaderRoute: typeof environmentappsAppStoreIndexRouteImport
      parentRoute: typeof environmentappsAppStoreRouteRoute
    }
    '/(environment)/(apps)/settings/people': {
      id: '/(environment)/(apps)/settings/people'
      path: '/people'
      fullPath: '/settings/people'
      preLoaderRoute: typeof environmentappsSettingsPeopleRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/settings/environments': {
      id: '/(environment)/(apps)/settings/environments'
      path: '/environments'
      fullPath: '/settings/environments'
      preLoaderRoute: typeof environmentappsSettingsEnvironmentsRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/settings/apps': {
      id: '/(environment)/(apps)/settings/apps'
      path: '/apps'
      fullPath: '/settings/apps'
      preLoaderRoute: typeof environmentappsSettingsAppsRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/settings/appearance': {
      id: '/(environment)/(apps)/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof environmentappsSettingsAppearanceRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/settings/accessibility': {
      id: '/(environment)/(apps)/settings/accessibility'
      path: '/accessibility'
      fullPath: '/settings/accessibility'
      preLoaderRoute: typeof environmentappsSettingsAccessibilityRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/app-store/search': {
      id: '/(environment)/(apps)/app-store/search'
      path: '/search'
      fullPath: '/app-store/search'
      preLoaderRoute: typeof environmentappsAppStoreSearchRouteImport
      parentRoute: typeof environmentappsAppStoreRouteRoute
    }
    '/(environment)/(apps)/app-store/arcade': {
      id: '/(environment)/(apps)/app-store/arcade'
      path: '/arcade'
      fullPath: '/app-store/arcade'
      preLoaderRoute: typeof environmentappsAppStoreArcadeRouteImport
      parentRoute: typeof environmentappsAppStoreRouteRoute
    }
    '/(environment)/(apps)/settings/general/': {
      id: '/(environment)/(apps)/settings/general/'
      path: '/general'
      fullPath: '/settings/general/'
      preLoaderRoute: typeof environmentappsSettingsGeneralIndexRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/settings/general/about': {
      id: '/(environment)/(apps)/settings/general/about'
      path: '/general/about'
      fullPath: '/settings/general/about'
      preLoaderRoute: typeof environmentappsSettingsGeneralAboutRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
  }
}

interface environmentappsAppStoreRouteRouteChildren {
  environmentappsAppStoreArcadeRoute: typeof environmentappsAppStoreArcadeRoute
  environmentappsAppStoreSearchRoute: typeof environmentappsAppStoreSearchRoute
  environmentappsAppStoreIndexRoute: typeof environmentappsAppStoreIndexRoute
}

const environmentappsAppStoreRouteRouteChildren: environmentappsAppStoreRouteRouteChildren =
  {
    environmentappsAppStoreArcadeRoute: environmentappsAppStoreArcadeRoute,
    environmentappsAppStoreSearchRoute: environmentappsAppStoreSearchRoute,
    environmentappsAppStoreIndexRoute: environmentappsAppStoreIndexRoute,
  }

const environmentappsAppStoreRouteRouteWithChildren =
  environmentappsAppStoreRouteRoute._addFileChildren(
    environmentappsAppStoreRouteRouteChildren,
  )

interface environmentappsSettingsRouteRouteChildren {
  environmentappsSettingsAccessibilityRoute: typeof environmentappsSettingsAccessibilityRoute
  environmentappsSettingsAppearanceRoute: typeof environmentappsSettingsAppearanceRoute
  environmentappsSettingsAppsRoute: typeof environmentappsSettingsAppsRoute
  environmentappsSettingsEnvironmentsRoute: typeof environmentappsSettingsEnvironmentsRoute
  environmentappsSettingsPeopleRoute: typeof environmentappsSettingsPeopleRoute
  environmentappsSettingsIndexRoute: typeof environmentappsSettingsIndexRoute
  environmentappsSettingsGeneralAboutRoute: typeof environmentappsSettingsGeneralAboutRoute
  environmentappsSettingsGeneralIndexRoute: typeof environmentappsSettingsGeneralIndexRoute
}

const environmentappsSettingsRouteRouteChildren: environmentappsSettingsRouteRouteChildren =
  {
    environmentappsSettingsAccessibilityRoute:
      environmentappsSettingsAccessibilityRoute,
    environmentappsSettingsAppearanceRoute:
      environmentappsSettingsAppearanceRoute,
    environmentappsSettingsAppsRoute: environmentappsSettingsAppsRoute,
    environmentappsSettingsEnvironmentsRoute:
      environmentappsSettingsEnvironmentsRoute,
    environmentappsSettingsPeopleRoute: environmentappsSettingsPeopleRoute,
    environmentappsSettingsIndexRoute: environmentappsSettingsIndexRoute,
    environmentappsSettingsGeneralAboutRoute:
      environmentappsSettingsGeneralAboutRoute,
    environmentappsSettingsGeneralIndexRoute:
      environmentappsSettingsGeneralIndexRoute,
  }

const environmentappsSettingsRouteRouteWithChildren =
  environmentappsSettingsRouteRoute._addFileChildren(
    environmentappsSettingsRouteRouteChildren,
  )

interface environmentappsRouteRouteChildren {
  environmentappsAppStoreRouteRoute: typeof environmentappsAppStoreRouteRouteWithChildren
  environmentappsSettingsRouteRoute: typeof environmentappsSettingsRouteRouteWithChildren
}

const environmentappsRouteRouteChildren: environmentappsRouteRouteChildren = {
  environmentappsAppStoreRouteRoute:
    environmentappsAppStoreRouteRouteWithChildren,
  environmentappsSettingsRouteRoute:
    environmentappsSettingsRouteRouteWithChildren,
}

const environmentappsRouteRouteWithChildren =
  environmentappsRouteRoute._addFileChildren(environmentappsRouteRouteChildren)

interface environmentornamentRouteRouteChildren {
  environmentornamentEnvironmentsRoute: typeof environmentornamentEnvironmentsRoute
  environmentornamentPeopleRoute: typeof environmentornamentPeopleRoute
  environmentornamentIndexRoute: typeof environmentornamentIndexRoute
}

const environmentornamentRouteRouteChildren: environmentornamentRouteRouteChildren =
  {
    environmentornamentEnvironmentsRoute: environmentornamentEnvironmentsRoute,
    environmentornamentPeopleRoute: environmentornamentPeopleRoute,
    environmentornamentIndexRoute: environmentornamentIndexRoute,
  }

const environmentornamentRouteRouteWithChildren =
  environmentornamentRouteRoute._addFileChildren(
    environmentornamentRouteRouteChildren,
  )

interface environmentRouteRouteChildren {
  environmentappsRouteRoute: typeof environmentappsRouteRouteWithChildren
  environmentornamentRouteRoute: typeof environmentornamentRouteRouteWithChildren
}

const environmentRouteRouteChildren: environmentRouteRouteChildren = {
  environmentappsRouteRoute: environmentappsRouteRouteWithChildren,
  environmentornamentRouteRoute: environmentornamentRouteRouteWithChildren,
}

const environmentRouteRouteWithChildren =
  environmentRouteRoute._addFileChildren(environmentRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  environmentRouteRoute: environmentRouteRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
