/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as environmentRouteRouteImport } from './routes/(environment)/route'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as environmentornamentRouteRouteImport } from './routes/(environment)/(ornament)/route'
import { Route as environmentornamentIndexRouteImport } from './routes/(environment)/(ornament)/index'
import { Route as environmentornamentPeopleRouteImport } from './routes/(environment)/(ornament)/people'
import { Route as environmentornamentEnvironmentsRouteImport } from './routes/(environment)/(ornament)/environments'
import { Route as environmentappsSettingsRouteRouteImport } from './routes/(environment)/(apps)/settings/route'
import { Route as environmentappsSettingsIndexRouteImport } from './routes/(environment)/(apps)/settings/index'
import { Route as environmentappsSettingsPeopleRouteImport } from './routes/(environment)/(apps)/settings/people'
import { Route as environmentappsSettingsGeneralRouteImport } from './routes/(environment)/(apps)/settings/general'
import { Route as environmentappsSettingsEnvironmentsRouteImport } from './routes/(environment)/(apps)/settings/environments'
import { Route as environmentappsSettingsAppsRouteImport } from './routes/(environment)/(apps)/settings/apps'
import { Route as environmentappsSettingsAppearanceRouteImport } from './routes/(environment)/(apps)/settings/appearance'
import { Route as environmentappsSettingsAccessibilityRouteImport } from './routes/(environment)/(apps)/settings/accessibility'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const environmentRouteRoute = environmentRouteRouteImport.update({
  id: '/(environment)',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const environmentornamentRouteRoute =
  environmentornamentRouteRouteImport.update({
    id: '/(ornament)',
    getParentRoute: () => environmentRouteRoute,
  } as any)
const environmentornamentIndexRoute =
  environmentornamentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => environmentornamentRouteRoute,
  } as any)
const environmentornamentPeopleRoute =
  environmentornamentPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => environmentornamentRouteRoute,
  } as any)
const environmentornamentEnvironmentsRoute =
  environmentornamentEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => environmentornamentRouteRoute,
  } as any)
const environmentappsSettingsRouteRoute =
  environmentappsSettingsRouteRouteImport.update({
    id: '/(apps)/settings',
    path: '/settings',
    getParentRoute: () => environmentRouteRoute,
  } as any)
const environmentappsSettingsIndexRoute =
  environmentappsSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsSettingsPeopleRoute =
  environmentappsSettingsPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsSettingsGeneralRoute =
  environmentappsSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsSettingsEnvironmentsRoute =
  environmentappsSettingsEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsSettingsAppsRoute =
  environmentappsSettingsAppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsSettingsAppearanceRoute =
  environmentappsSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)
const environmentappsSettingsAccessibilityRoute =
  environmentappsSettingsAccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => environmentappsSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/settings': typeof environmentappsSettingsRouteRouteWithChildren
  '/environments': typeof environmentornamentEnvironmentsRoute
  '/people': typeof environmentornamentPeopleRoute
  '/': typeof environmentornamentIndexRoute
  '/settings/accessibility': typeof environmentappsSettingsAccessibilityRoute
  '/settings/appearance': typeof environmentappsSettingsAppearanceRoute
  '/settings/apps': typeof environmentappsSettingsAppsRoute
  '/settings/environments': typeof environmentappsSettingsEnvironmentsRoute
  '/settings/general': typeof environmentappsSettingsGeneralRoute
  '/settings/people': typeof environmentappsSettingsPeopleRoute
  '/settings/': typeof environmentappsSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/environments': typeof environmentornamentEnvironmentsRoute
  '/people': typeof environmentornamentPeopleRoute
  '/': typeof environmentornamentIndexRoute
  '/settings/accessibility': typeof environmentappsSettingsAccessibilityRoute
  '/settings/appearance': typeof environmentappsSettingsAppearanceRoute
  '/settings/apps': typeof environmentappsSettingsAppsRoute
  '/settings/environments': typeof environmentappsSettingsEnvironmentsRoute
  '/settings/general': typeof environmentappsSettingsGeneralRoute
  '/settings/people': typeof environmentappsSettingsPeopleRoute
  '/settings': typeof environmentappsSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(environment)': typeof environmentRouteRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/(environment)/(ornament)': typeof environmentornamentRouteRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/(environment)/(apps)/settings': typeof environmentappsSettingsRouteRouteWithChildren
  '/(environment)/(ornament)/environments': typeof environmentornamentEnvironmentsRoute
  '/(environment)/(ornament)/people': typeof environmentornamentPeopleRoute
  '/(environment)/(ornament)/': typeof environmentornamentIndexRoute
  '/(environment)/(apps)/settings/accessibility': typeof environmentappsSettingsAccessibilityRoute
  '/(environment)/(apps)/settings/appearance': typeof environmentappsSettingsAppearanceRoute
  '/(environment)/(apps)/settings/apps': typeof environmentappsSettingsAppsRoute
  '/(environment)/(apps)/settings/environments': typeof environmentappsSettingsEnvironmentsRoute
  '/(environment)/(apps)/settings/general': typeof environmentappsSettingsGeneralRoute
  '/(environment)/(apps)/settings/people': typeof environmentappsSettingsPeopleRoute
  '/(environment)/(apps)/settings/': typeof environmentappsSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/settings'
    | '/environments'
    | '/people'
    | '/'
    | '/settings/accessibility'
    | '/settings/appearance'
    | '/settings/apps'
    | '/settings/environments'
    | '/settings/general'
    | '/settings/people'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/environments'
    | '/people'
    | '/'
    | '/settings/accessibility'
    | '/settings/appearance'
    | '/settings/apps'
    | '/settings/environments'
    | '/settings/general'
    | '/settings/people'
    | '/settings'
  id:
    | '__root__'
    | '/(environment)'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/(environment)/(ornament)'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/(environment)/(apps)/settings'
    | '/(environment)/(ornament)/environments'
    | '/(environment)/(ornament)/people'
    | '/(environment)/(ornament)/'
    | '/(environment)/(apps)/settings/accessibility'
    | '/(environment)/(apps)/settings/appearance'
    | '/(environment)/(apps)/settings/apps'
    | '/(environment)/(apps)/settings/environments'
    | '/(environment)/(apps)/settings/general'
    | '/(environment)/(apps)/settings/people'
    | '/(environment)/(apps)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  environmentRouteRoute: typeof environmentRouteRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(environment)': {
      id: '/(environment)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof environmentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(environment)/(ornament)': {
      id: '/(environment)/(ornament)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof environmentornamentRouteRouteImport
      parentRoute: typeof environmentRouteRoute
    }
    '/(environment)/(ornament)/': {
      id: '/(environment)/(ornament)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof environmentornamentIndexRouteImport
      parentRoute: typeof environmentornamentRouteRoute
    }
    '/(environment)/(ornament)/people': {
      id: '/(environment)/(ornament)/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof environmentornamentPeopleRouteImport
      parentRoute: typeof environmentornamentRouteRoute
    }
    '/(environment)/(ornament)/environments': {
      id: '/(environment)/(ornament)/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof environmentornamentEnvironmentsRouteImport
      parentRoute: typeof environmentornamentRouteRoute
    }
    '/(environment)/(apps)/settings': {
      id: '/(environment)/(apps)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof environmentappsSettingsRouteRouteImport
      parentRoute: typeof environmentRouteRoute
    }
    '/(environment)/(apps)/settings/': {
      id: '/(environment)/(apps)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof environmentappsSettingsIndexRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/settings/people': {
      id: '/(environment)/(apps)/settings/people'
      path: '/people'
      fullPath: '/settings/people'
      preLoaderRoute: typeof environmentappsSettingsPeopleRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/settings/general': {
      id: '/(environment)/(apps)/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof environmentappsSettingsGeneralRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/settings/environments': {
      id: '/(environment)/(apps)/settings/environments'
      path: '/environments'
      fullPath: '/settings/environments'
      preLoaderRoute: typeof environmentappsSettingsEnvironmentsRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/settings/apps': {
      id: '/(environment)/(apps)/settings/apps'
      path: '/apps'
      fullPath: '/settings/apps'
      preLoaderRoute: typeof environmentappsSettingsAppsRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/settings/appearance': {
      id: '/(environment)/(apps)/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof environmentappsSettingsAppearanceRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
    '/(environment)/(apps)/settings/accessibility': {
      id: '/(environment)/(apps)/settings/accessibility'
      path: '/accessibility'
      fullPath: '/settings/accessibility'
      preLoaderRoute: typeof environmentappsSettingsAccessibilityRouteImport
      parentRoute: typeof environmentappsSettingsRouteRoute
    }
  }
}

interface environmentornamentRouteRouteChildren {
  environmentornamentEnvironmentsRoute: typeof environmentornamentEnvironmentsRoute
  environmentornamentPeopleRoute: typeof environmentornamentPeopleRoute
  environmentornamentIndexRoute: typeof environmentornamentIndexRoute
}

const environmentornamentRouteRouteChildren: environmentornamentRouteRouteChildren =
  {
    environmentornamentEnvironmentsRoute: environmentornamentEnvironmentsRoute,
    environmentornamentPeopleRoute: environmentornamentPeopleRoute,
    environmentornamentIndexRoute: environmentornamentIndexRoute,
  }

const environmentornamentRouteRouteWithChildren =
  environmentornamentRouteRoute._addFileChildren(
    environmentornamentRouteRouteChildren,
  )

interface environmentappsSettingsRouteRouteChildren {
  environmentappsSettingsAccessibilityRoute: typeof environmentappsSettingsAccessibilityRoute
  environmentappsSettingsAppearanceRoute: typeof environmentappsSettingsAppearanceRoute
  environmentappsSettingsAppsRoute: typeof environmentappsSettingsAppsRoute
  environmentappsSettingsEnvironmentsRoute: typeof environmentappsSettingsEnvironmentsRoute
  environmentappsSettingsGeneralRoute: typeof environmentappsSettingsGeneralRoute
  environmentappsSettingsPeopleRoute: typeof environmentappsSettingsPeopleRoute
  environmentappsSettingsIndexRoute: typeof environmentappsSettingsIndexRoute
}

const environmentappsSettingsRouteRouteChildren: environmentappsSettingsRouteRouteChildren =
  {
    environmentappsSettingsAccessibilityRoute:
      environmentappsSettingsAccessibilityRoute,
    environmentappsSettingsAppearanceRoute:
      environmentappsSettingsAppearanceRoute,
    environmentappsSettingsAppsRoute: environmentappsSettingsAppsRoute,
    environmentappsSettingsEnvironmentsRoute:
      environmentappsSettingsEnvironmentsRoute,
    environmentappsSettingsGeneralRoute: environmentappsSettingsGeneralRoute,
    environmentappsSettingsPeopleRoute: environmentappsSettingsPeopleRoute,
    environmentappsSettingsIndexRoute: environmentappsSettingsIndexRoute,
  }

const environmentappsSettingsRouteRouteWithChildren =
  environmentappsSettingsRouteRoute._addFileChildren(
    environmentappsSettingsRouteRouteChildren,
  )

interface environmentRouteRouteChildren {
  environmentornamentRouteRoute: typeof environmentornamentRouteRouteWithChildren
  environmentappsSettingsRouteRoute: typeof environmentappsSettingsRouteRouteWithChildren
}

const environmentRouteRouteChildren: environmentRouteRouteChildren = {
  environmentornamentRouteRoute: environmentornamentRouteRouteWithChildren,
  environmentappsSettingsRouteRoute:
    environmentappsSettingsRouteRouteWithChildren,
}

const environmentRouteRouteWithChildren =
  environmentRouteRoute._addFileChildren(environmentRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  environmentRouteRoute: environmentRouteRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
